-- =============================================================================
-- 2026-08-13_legacy_import.sql
--
-- One-time production import of the legacy SmartCard database into
-- SmartCard 2.0. Executed 2026-08-13 against project crpsbnbegeoqtlgshltt.
--
-- WHY THIS LIVES IN supabase/seed/ AND NOT supabase/migrations/
--   Migrations must be replayable from zero on any environment. This file
--   inserts 9,757 rows of *specific production data* with hard-coded primary
--   keys and unique values (`legacy_user_id`, `card_code`, `legacy_card_id`).
--   Replaying it on a fresh database that already ran it — or on a developer's
--   local stack — fails on unique-constraint violations, which would make
--   `supabase db reset` permanently broken. Schema changes belong in
--   migrations; this is operational data, and it runs exactly once.
--
--   The one genuinely structural piece of this import — the `legacy` schema and
--   the `legacy.contactexchange` table — IS a migration, and lives at
--   supabase/migrations/20260813171953_legacy_schema_contactexchange_archive.sql.
--   Only the row loading is here.
--
-- WHY THE ROW DATA IS NOT IN THIS FILE
--   The source export contains real personal data: 337 people's emails, phone
--   numbers and free-text bios, plus 1,813 captured contact records. Checking
--   9,757 rows of that into git would publish it to every clone of the repo
--   forever, including any future public one, and git history cannot be
--   un-published. This file therefore records the *transformation* — the rules,
--   the judgement calls, and the checks — which is the part a reviewer needs and
--   the part that is worth version-controlling. The rows themselves were
--   generated by the accompanying script from a local export and streamed
--   straight to the database.
--
--   To reproduce: run 2026-08-13_legacy_import_generator.py against the export,
--   then execute the emitted chunks in the order given under "LOAD ORDER".
--
-- SOURCE
--   core-data-export.sql — a Postgres COPY dump of the legacy database:
--     users            337 rows
--     card           7,142 rows
--     sociallink       466 rows
--     contactexchange 1,813 rows
-- =============================================================================


-- =============================================================================
-- STEP 0 — the legacy-id -> UUID map (temporary)
-- =============================================================================
-- Every legacy table references users by integer id. The new schema uses random
-- UUIDs. Rather than embed the mapping in each generated INSERT — where a single
-- transcription slip would silently attach a card to the wrong person — the map
-- is materialised once as a table, and every downstream insert JOINs against it.
-- A wrong id then cannot produce a wrong row: it produces no row at all, and the
-- row-count check catches it.
--
-- The UUIDs are random (uuid4), generated once and frozen, per §6.2 ("new UUID").
-- They are deliberately NOT derived from the legacy id — a derivable UUID would
-- leak the legacy id and the signup order into every public identifier.
--
-- This schema is temporary and was dropped at the end of the run (STEP 6).
-- Dropping it loses nothing: the mapping survives permanently and canonically as
-- public.users.legacy_user_id -> public.users.id, which is unique on both sides.

create schema if not exists legacy_staging;

create table legacy_staging.user_id_map (
  legacy_user_id bigint primary key,
  new_user_id    uuid   not null unique
);

-- ... 337 rows loaded here (see generator: `stage_*.sql`) ...


-- =============================================================================
-- STEP 1 — public.users (337 rows)
-- =============================================================================
-- Shape of every generated statement:
--
--   insert into public.users (id, kinde_user_id, email, ..., legacy_user_id, ...)
--   select m.new_user_id, v.kinde, v.email::extensions.citext, ...
--   from (values (…), (…), …) as v(legacy_id, kinde, email, …)
--   join legacy_staging.user_id_map m on m.legacy_user_id = v.legacy_id;
--
-- Note that `users` resolves its own id through the map too. That is not
-- redundancy — it is what guarantees `users.id` and the map can never disagree,
-- so cards and social_links cannot end up pointing at a user id that was never
-- inserted.
--
-- COLUMN MAPPING (per §6.2), with the decisions that §6.2 left open:
--
--   loginpassword -> DROPPED. Never selected out of the export, never written
--     to any generated file, never transmitted, never logged. The legacy bcrypt
--     hashes have no role in the new system — Kinde is the sole identity
--     provider (§5.3) — so importing them would create a credential store that
--     nothing authenticates against and everything could leak. Verified absent
--     afterwards by the sweep in STEP 5.
--
--   userstatus -> status. JUDGEMENT CALL: the export contains exactly ONE
--     distinct value across all 337 rows — '1'. There is no legacy row from
--     which a 'suspended' or 'deleted' state could be inferred, and the
--     generator asserts this (`assert set(userstatus) == {'1'}`) so the mapping
--     cannot be silently wrong if the export ever changes. '1' -> 'active'.
--     Nobody was defaulted into a restrictive state on a guess: 'suspended' and
--     'deleted' both remove access, and inventing either from an unlabelled
--     integer would lock a real person out of their own account.
--
--   profilephoto -> photo_path: LEFT NULL FOR EVERY ROW in this pass, by
--     instruction. See 2026-08-13_legacy_photo_paths.csv and §6.5 — the paths
--     are preserved there so a follow-up pass can upload the files and
--     backfill `photo_path` without re-reading the legacy database.
--
--   '' -> NULL for bio (21 rows), company_name (15), company_role (13).
--     An empty string and NULL mean the same thing here — "not filled in" — and
--     collapsing them means UI code and `coalesce` behave the same way for every
--     user instead of depending on which legacy form version they used.
--     first_name, last_name and phone_number had no empty strings to collapse.
--
--   email / username -> extensions.citext. Cast explicitly rather than left to
--     implicit coercion so a duplicate that differs only in case fails loudly
--     on the unique index at import time, not later at signup.
--
-- ... 337 rows loaded here (see generator: `users_*.sql`) ...


-- =============================================================================
-- STEP 2 — public.cards (7,142 rows: 333 assigned + 6,809 unassigned)
-- =============================================================================
--   cardid -> card_code, copied unchanged. §2.2/Q1 established that the 48-bit
--     hex suffix IS the card secret and that all 7,142 are unique, so
--     regenerating codes would invalidate physical inventory for no gain.
--     Re-verified against the export before loading: every suffix is exactly 12
--     hex characters and all 7,142 are distinct.
--
--   cardstatus -> status. The 0/1 -> unassigned/assigned mapping was NOT
--     assumed from the column name; it was checked against the data. The
--     generator asserts, for all 7,142 rows, that `cardstatus = '1'` holds if
--     and only if `ownerid` is non-null. That is what makes the mapping a fact
--     rather than a reasonable-sounding guess — and it also proves the import
--     cannot violate `cards_assigned_requires_owner`.
--
--   ownerid -> owner_user_id, via the map join. Every one of the 333 non-null
--     owner ids resolved; 0 orphans (verified in STEP 5). 314 distinct owners.
--
-- The 6,809 unassigned rows are inserted with only (card_code, created_at,
-- legacy_card_id): `status` takes its 'unassigned' default and owner_user_id /
-- assigned_at are NULL for every one of them, so emitting those literals 6,809
-- times would add bulk without adding information.
--
-- ... 7,142 rows loaded here (see generator: `cards_assigned_*.sql`,
--     `cards_unassigned_*.sql`) ...


-- =============================================================================
-- STEP 3 — public.social_links (465 of 466 rows; 1 skipped)
-- =============================================================================
-- §6.4 says "validate/normalize URLs on the way in". The rule applied uniformly
-- to all 466 rows, and why each branch is safe:
--
--   (a) Already a single well-formed http(s) URL with no whitespace -> imported,
--       with the scheme lowercased. URI schemes are case-insensitive (RFC 3986
--       §3.1) and lowercase is the specified normal form, so `Https://` ->
--       `https://` cannot change which resource is addressed. 1 row (legacy
--       sociallink id 403) needed this.
--
--   (b) Contains whitespace but exactly ONE http(s) token -> that token is
--       taken. Whitespace terminates a URL in every parser, so the trailing
--       words were never part of the link and nothing is discarded. 7 rows, all
--       LinkedIn (legacy ids 33, 83, 203, 213, 249, 317, 442).
--
--   (c) More than one http(s) token in free text -> SKIPPED, not guessed.
--       1 row: legacy sociallink id 85 (legacy user 37, platform Instagram).
--       Choosing one of two candidate URLs would publish a link to a real
--       person's account on a coin flip. A missing link is a visibly missing
--       link the owner can re-add; a wrong link points strangers at someone
--       else's profile and looks correct. Failing closed is the cheaper error.
--
--   http:// is deliberately NOT upgraded to https:// (4 rows). Rewriting the
--   scheme changes which resource is requested based on an assumption about a
--   remote host we do not control. That is a guess wearing a normalisation's
--   clothing.
--
--   `updateddatetime = '-infinity'` (58 rows) -> substituted with the row's own
--   created_at. `-infinity` is a Postgres sentinel, not a time: it survives the
--   column type but breaks JS `Date` parsing and cannot be rendered, so it would
--   surface as a client-side crash on a profile page. created_at is the only
--   defensible substitute — the row demonstrably existed then. The 132 ordinary
--   rows where updated < created are NOT touched: those are real timestamps,
--   they only look odd, and rewriting them would destroy true data to satisfy
--   an aesthetic expectation.
--
--   6 exact duplicate (user, platform, url) rows were imported faithfully
--   rather than de-duplicated. There is no unique constraint on that triple, so
--   the legacy state is representable; silently dropping rows during a
--   migration hides data the owner may want to clean up deliberately.
--
-- ... 465 rows loaded here (see generator: `links_*.sql`) ...


-- =============================================================================
-- STEP 4 — legacy.contactexchange (1,813 rows)
-- =============================================================================
-- NOT mapped into connections/meetings — see §6.7 and the header of migration
-- 20260813171953, which explains at length why turning one-directional capture
-- data into graph edges would violate the product's core rule.
--
-- Loaded as a faithful column-for-column mirror with NO transformation at all:
-- legacy integer user ids preserved as-is, no UUID remapping, no FK, empty-string
-- notes left as empty strings rather than collapsed to NULL (unlike users —
-- here the point is to preserve exactly what the old system stored).
--
-- Checked at import time, for information only: all 1,813 owner ids and all 518
-- non-null sender ids do resolve to imported users. The FK is omitted on
-- purpose, not because it would fail.
--
-- ... 1,813 rows loaded here (see generator: `contactexchange_*.sql`) ...


-- =============================================================================
-- STEP 5 — verification
-- =============================================================================

-- 5a. Row counts and referential integrity.
-- Expected: 337 / 7142 / 333 / 6809 / 7142 / 465 / 1813, and 0 for every
-- "orphan"/"without"/"with" column below.
select
  (select count(*) from public.users)                                                as users_total,
  (select count(*) from public.cards)                                                as cards_total,
  (select count(*) from public.cards where status = 'assigned')                      as cards_assigned,
  (select count(*) from public.cards where status = 'unassigned')                    as cards_unassigned,
  (select count(distinct card_code) from public.cards)                               as cards_distinct_codes,
  (select count(*) from public.social_links)                                         as social_links_total,
  (select count(*) from legacy.contactexchange)                                      as contactexchange_total,
  (select count(*) from public.cards c
     where c.owner_user_id is not null
       and not exists (select 1 from public.users u where u.id = c.owner_user_id))   as orphan_card_owners,
  (select count(*) from public.social_links s
     where not exists (select 1 from public.users u where u.id = s.user_id))         as orphan_social_links,
  (select count(*) from public.cards where status = 'assigned' and owner_user_id is null)     as assigned_without_owner,
  (select count(*) from public.cards where status = 'unassigned' and owner_user_id is not null) as unassigned_with_owner,
  (select count(*) from public.users where photo_path is not null)                   as users_with_photo_path,
  (select count(*) from public.users where status <> 'active')                       as users_not_active,
  (select count(distinct legacy_user_id) from public.users)                          as distinct_legacy_user_ids;


-- 5b. No password-shaped value survives anywhere in public.users.
-- Deliberately column-agnostic: rather than checking the columns we expect to be
-- clean, this converts each row to JSON and scans EVERY text-ish value, so a
-- hash that ended up in the wrong column (e.g. pasted into `bio`) is still
-- caught. Matches bcrypt/argon2/scrypt/PBKDF2/MD5-crypt/SHA-crypt prefixes, LDAP
-- {SSHA}-style prefixes, and any long unbroken base64-ish blob.
-- Expected: 0.
select count(*) filter (where hit) as password_shaped_hits,
       count(*)                    as rows_scanned
from (
  select exists (
           select 1
           from jsonb_each_text(to_jsonb(u)) kv(k, v)
           where v ~ '^\$(2[abxy]?|1|5|6|argon2[id]{1,2}|scrypt|pbkdf2)\$'
              or v ~ '^\{(SSHA|SHA|MD5|CRYPT)\}'
              or (length(v) between 40 and 200
                  and v ~ '^[A-Za-z0-9+/._$-]+$'
                  and v !~ '[ @]'
                  and k not in ('id', 'kinde_user_id'))
         ) as hit
  from public.users u
) t;


-- 5c. Content checksum — the check that row counts cannot make.
-- The rows were hand-transmitted as SQL text, so a correct count proves nothing
-- about a mangled character inside a bio. This computes an order-independent
-- digest of the actual column values, which is compared against the identical
-- digest computed locally from the source export. They must match exactly.
--
-- Two details that make the two sides comparable:
--   * timestamps are canonicalised through to_char(... at time zone 'UTC') so
--     that '…10.585+00' and '…10.585000' are the same string on both sides;
--   * NULL gets an explicit sentinel, because ''||NULL is NULL and would
--     otherwise make an all-NULL row indistinguishable from any other.
-- `order by h collate "C"` pins byte ordering so the digest is locale-independent.
--
-- Shown here for legacy.contactexchange; the same construction was run for
-- users, cards and social_links.
-- Expected (contactexchange): aef81c1bd937ee2204ce190f4d2dad47
with rowhash as (
  select md5(
    legacy_id::text || '|~|' ||
    card_owner_legacy_user_id::text || '|~|' ||
    coalesce(sender_legacy_user_id::text, '<<NULL>>') || '|~|' ||
    coalesce(sender_name,  '<<NULL>>') || '|~|' ||
    coalesce(sender_email, '<<NULL>>') || '|~|' ||
    coalesce(sender_phone, '<<NULL>>') || '|~|' ||
    coalesce(notes,        '<<NULL>>') || '|~|' ||
    to_char(created_at at time zone 'UTC', 'YYYY-MM-DD HH24:MI:SS.US')
  ) as h
  from legacy.contactexchange
)
select count(*) as rows, md5(string_agg(h, '' order by h collate "C")) as content_md5
from rowhash;


-- 5d. The `legacy` schema is unreachable from application code.
-- §6.7's guarantee is "not reachable from application code", and the migration
-- header claims defence in depth. This checks the depth rather than trusting the
-- schema name: even if PostgREST were reconfigured to expose `legacy`, anon and
-- authenticated have no USAGE on the schema, no SELECT on the table, and the
-- table has RLS enabled + FORCEd with zero policies.
-- Expected: false, false, false, false, true, true, 0, 1.
select
  has_schema_privilege('anon',          'legacy', 'USAGE')                    as anon_schema_usage,
  has_schema_privilege('authenticated', 'legacy', 'USAGE')                    as auth_schema_usage,
  has_table_privilege ('anon',          'legacy.contactexchange', 'SELECT')   as anon_select,
  has_table_privilege ('authenticated', 'legacy.contactexchange', 'SELECT')   as auth_select,
  (select relrowsecurity      from pg_class where oid = 'legacy.contactexchange'::regclass) as rls_enabled,
  (select relforcerowsecurity from pg_class where oid = 'legacy.contactexchange'::regclass) as rls_forced,
  (select count(*) from pg_policies where schemaname = 'legacy')              as policies_on_legacy,
  (select count(*) from information_schema.tables where table_schema = 'legacy') as tables_in_legacy;

-- And: no `pgrst.*` GUC is persisted anywhere in this database, so PostgREST is
-- running on the project's configured exposed-schema list and nothing in this
-- import added `legacy` to it. Expected: zero rows from the first branch.
select coalesce(d.datname, '(all databases)') as database,
       coalesce(r.rolname, '(all roles)')     as role,
       s.setconfig
from pg_db_role_setting s
left join pg_database d on d.oid = s.setdatabase
left join pg_roles    r on r.oid = s.setrole
where exists (select 1 from unnest(s.setconfig) c where c like 'pgrst.%');


-- 5e. Linkage proof — run BEFORE dropping legacy_staging, since this is the last
-- moment the map exists to be checked against.
-- Expected: 337, 337, 0, 0, 314, 0, 0, 0, 0.
select
  (select count(*) from legacy_staging.user_id_map)                                   as map_rows,
  (select count(*) from legacy_staging.user_id_map m
     join public.users u on u.legacy_user_id = m.legacy_user_id
    where u.id = m.new_user_id)                                                       as users_matching_map,
  (select count(*) from public.users u
     where not exists (select 1 from legacy_staging.user_id_map m
                        where m.legacy_user_id = u.legacy_user_id))                   as users_not_in_map,
  (select count(*) from legacy_staging.user_id_map m
     where not exists (select 1 from public.users u
                        where u.legacy_user_id = m.legacy_user_id))                   as map_entries_without_user,
  (select count(distinct owner_user_id) from public.cards where owner_user_id is not null) as distinct_card_owners,
  (select count(*) from public.cards c
     where c.owner_user_id is not null
       and not exists (select 1 from legacy_staging.user_id_map m
                        where m.new_user_id = c.owner_user_id))                       as card_owners_off_map,
  (select count(*) from public.social_links s
     where not exists (select 1 from legacy_staging.user_id_map m
                        where m.new_user_id = s.user_id))                             as social_links_off_map,
  (select count(*) from legacy.contactexchange x
     where not exists (select 1 from public.users u
                        where u.legacy_user_id = x.card_owner_legacy_user_id))        as cx_unresolvable_owners,
  (select count(*) from legacy.contactexchange x
     where x.sender_legacy_user_id is not null
       and not exists (select 1 from public.users u
                        where u.legacy_user_id = x.sender_legacy_user_id))            as cx_unresolvable_senders;


-- =============================================================================
-- STEP 6 — remove scratch state
-- =============================================================================
-- Safe only after 5e passes. The mapping is not lost: public.users.legacy_user_id
-- -> public.users.id is unique on both sides and is the permanent, canonical
-- version of what this table held.
drop schema if exists legacy_staging cascade;


-- =============================================================================
-- LOAD ORDER (dependency order, per §6.1 step 4)
-- =============================================================================
--   1. legacy_staging schema + user_id_map DDL          (STEP 0)
--   2. stage_*.sql              337 rows
--   3. users_*.sql              337 rows                (needs the map)
--   4. cards_assigned_*.sql     333 rows                (needs users)
--      cards_unassigned_*.sql 6,809 rows
--   5. links_*.sql              465 rows                (needs users)
--   6. contactexchange_*.sql  1,813 rows                (needs the migration's
--                                                        table; independent of
--                                                        the map)
--   7. verification (STEP 5), then drop legacy_staging  (STEP 6)
--
-- Photos are NOT part of this pass — see 2026-08-13_legacy_photo_paths.csv.
-- =============================================================================
